import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

const translations = {
  id: {
    dashboard: 'Dashboard',
    projects: 'Proyek',
    units: 'Unit',
    siteplan: 'Siteplan',
    crm: 'CRM',
    leads: 'Leads',
    lead_import: 'Import Lead',
    deals: 'Deals',
    whatsapp: 'WhatsApp',
    dev_report: 'Laporan Dev',
    settings: 'Pengaturan',
    logout: 'Keluar',
    login: 'Masuk',
    register: 'Daftar',
    email: 'Email',
    password: 'Kata Sandi',
    name: 'Nama',
    search: 'Cari...',
    filter: 'Filter',
    export: 'Ekspor',
    add_new: 'Tambah Baru',
    save: 'Simpan',
    cancel: 'Batal',
    delete: 'Hapus',
    edit: 'Edit',
    view: 'Lihat',
    status: 'Status',
    actions: 'Aksi',
    total: 'Total',
    available: 'Tersedia',
    reserved: 'Direservasi',
    booked: 'Dibooking',
    sold: 'Terjual',
    active: 'Aktif',
    new_lead: 'Lead Baru',
    contacted: 'Dihubungi',
    prospect: 'Prospek',
    no_response: 'Tidak Respon',
    lost: 'Hilang',
    welcome_back: 'Selamat Datang Kembali',
    overview: 'Ringkasan',
    revenue: 'Pendapatan',
    total_projects: 'Total Proyek',
    total_units: 'Total Unit',
    total_leads: 'Total Leads',
    total_deals: 'Total Deals',
    recent_activities: 'Aktivitas Terbaru',
    lead_sources: 'Sumber Lead',
    quick_actions: 'Aksi Cepat',
    unit_summary: 'Ringkasan Unit',
    deal_pipeline: 'Pipeline Deal',
    project_name: 'Nama Proyek',
    location: 'Lokasi',
    description: 'Deskripsi',
    price: 'Harga',
    block: 'Blok',
    type: 'Tipe',
    phone: 'Telepon',
    source: 'Sumber',
    campaign: 'Kampanye',
    assigned_to: 'Ditugaskan Ke',
    notes: 'Catatan',
    customer: 'Pelanggan',
    unit: 'Unit',
    payment_method: 'Metode Pembayaran',
    send_message: 'Kirim Pesan',
    message: 'Pesan',
    recipient: 'Penerima',
    template: 'Template',
    messages_log: 'Log Pesan',
    development_report: 'Laporan Pengembangan',
    module: 'Modul',
    feature: 'Fitur',
    priority: 'Prioritas',
    completed: 'Selesai',
    in_progress: 'Sedang Berjalan',
    not_started: 'Belum Dimulai',
    milestone: 'Milestone',
    blockers: 'Hambatan',
    sales_view: 'Mode Penjualan',
    construction_view: 'Mode Konstruksi',
    finance_view: 'Mode Keuangan',
    management_view: 'Mode Manajemen',
    import_from_csv: 'Import dari CSV',
    import_from_ads: 'Import dari Ads',
    import_leads: 'Import Leads',
    select_project: 'Pilih Proyek',
    all_projects: 'Semua Proyek',
    all_statuses: 'Semua Status',
    no_data: 'Tidak ada data',
    loading: 'Memuat...',
    confirm_delete: 'Yakin ingin menghapus?',
    finance: 'Finance',
    construction: 'Konstruksi',
    notifications: 'Notifikasi',
    appointments: 'Jadwal',
    billing: 'Tagihan',
    payments: 'Pembayaran',
    collection: 'Penagihan',
    progress: 'Progress',
    qc: 'Quality Control',
    overdue: 'Overdue',
    auto_followup: 'Auto Follow-Up',
  },
  en: {
    dashboard: 'Dashboard',
    projects: 'Projects',
    units: 'Units',
    siteplan: 'Siteplan',
    crm: 'CRM',
    leads: 'Leads',
    lead_import: 'Lead Import',
    deals: 'Deals',
    whatsapp: 'WhatsApp',
    dev_report: 'Dev Report',
    settings: 'Settings',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    search: 'Search...',
    filter: 'Filter',
    export: 'Export',
    add_new: 'Add New',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    view: 'View',
    status: 'Status',
    actions: 'Actions',
    total: 'Total',
    available: 'Available',
    reserved: 'Reserved',
    booked: 'Booked',
    sold: 'Sold',
    active: 'Active',
    new_lead: 'New Lead',
    contacted: 'Contacted',
    prospect: 'Prospect',
    no_response: 'No Response',
    lost: 'Lost',
    welcome_back: 'Welcome Back',
    overview: 'Overview',
    revenue: 'Revenue',
    total_projects: 'Total Projects',
    total_units: 'Total Units',
    total_leads: 'Total Leads',
    total_deals: 'Total Deals',
    recent_activities: 'Recent Activities',
    lead_sources: 'Lead Sources',
    quick_actions: 'Quick Actions',
    unit_summary: 'Unit Summary',
    deal_pipeline: 'Deal Pipeline',
    project_name: 'Project Name',
    location: 'Location',
    description: 'Description',
    price: 'Price',
    block: 'Block',
    type: 'Type',
    phone: 'Phone',
    source: 'Source',
    campaign: 'Campaign',
    assigned_to: 'Assigned To',
    notes: 'Notes',
    customer: 'Customer',
    unit: 'Unit',
    payment_method: 'Payment Method',
    send_message: 'Send Message',
    message: 'Message',
    recipient: 'Recipient',
    template: 'Template',
    messages_log: 'Messages Log',
    development_report: 'Development Report',
    module: 'Module',
    feature: 'Feature',
    priority: 'Priority',
    completed: 'Completed',
    in_progress: 'In Progress',
    not_started: 'Not Started',
    milestone: 'Milestone',
    blockers: 'Blockers',
    sales_view: 'Sales View',
    construction_view: 'Construction View',
    finance_view: 'Finance View',
    management_view: 'Management View',
    import_from_csv: 'Import from CSV',
    import_from_ads: 'Import from Ads',
    import_leads: 'Import Leads',
    select_project: 'Select Project',
    all_projects: 'All Projects',
    all_statuses: 'All Statuses',
    no_data: 'No data',
    loading: 'Loading...',
    confirm_delete: 'Are you sure you want to delete?',
    finance: 'Finance',
    construction: 'Construction',
    notifications: 'Notifications',
    appointments: 'Appointments',
    billing: 'Billing',
    payments: 'Payments',
    collection: 'Collection',
    progress: 'Progress',
    qc: 'Quality Control',
    overdue: 'Overdue',
    auto_followup: 'Auto Follow-Up',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('sipro_lang') || 'id');

  const t = (key) => translations[lang]?.[key] || translations['en']?.[key] || key;

  const toggleLang = () => {
    const newLang = lang === 'id' ? 'en' : 'id';
    setLang(newLang);
    localStorage.setItem('sipro_lang', newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, t, toggleLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
